version: '3'

services:
  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    command: bash scripts/run-scraper.sh
    volumes:
      - ./ipublica_data/scraper:/src/data
  neo4j:
    image: neo4j:4.0.1
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./ipublica_data/neo4j:/data
