version: '3'

services:
  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    command: bash scripts/run-scraper.sh
    volumes:
      - ./ipublica_data/scraper:/src/data

  neo4j:
    image: neo4j:3.5
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/unholster
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*

    volumes:
      - ./ipublica_data/neo4j:/var/lib/neo4j/data
      - ./ipublica_data/neo4j_plugins:/plugins

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    volumes:
      - ./ipublica_data/elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    ports:
      - 5601:5601
